export const SERVER_INSTRUCTIONS = [
  "Recruiterflow (ATS / CRM) — intent-level tools backed by a server-side cache (Cloudflare worker + D1). All resolution (fuzzy names, field aliases, stage landmarks) happens server-side; the MCP forwards what you send.",
  "",
  "Pass natural strings everywhere — candidate names, job names, stage names, owner names, technology values. Numeric (or numeric-string '984') ids bypass fuzzy and go direct — pass IDs back when you have them from prior turns. Move-stage / log-interview auto-commit when (candidate, job, stage) uniquely identifies a tuple, even if `candidate` alone was ambiguous — single round-trip is the design goal.",
  "",
  "Tools:",
  "  - rf_candidate_get         — ONE specific person (id or fuzzy name). Auto-disambiguates if name is ambiguous. CANNOT use company / owner / stage / technology hints.",
  "  - rf_candidate_search      — RANKED LIST / multi-match. Filter composition (company, owner, technology, stage [paired with job], role, segment, date windows) and/or fuzzy name. 'Jerry at Acme' goes here, not get.",
  "  - rf_candidate_move_stage  — move a candidate to a pipeline stage",
  "  - rf_candidate_log_interview — write an Interview activity (calendar handoff via response)",
  "  - rf_candidate_add_note    — write a note on a candidate's RF timeline (markdown body, server renders to HTML)",
  "  - rf_job_pipeline          — JOB PIPELINE VIEW: candidates grouped by stage. Use for ANY pipeline / stage-progress / 'submitted' / 'in <stage>' query.",
  "  - rf_job_candidates_filter — flat (non-grouped) job-side list. ONLY when pipeline grouping isn't wanted — custom field projections / analytics-style filters. NOT the right tool for pipeline prompts.",
  "  - rf_cache_status          — diagnostic only, when the user asks about data freshness",
  "  - rf_candidate_call_notes  — write structured call notes from a recent Dialpad screening call (three-step flow)",
  "",
  "Candidate lookup routing — the line is intent + narrowing context:",
  "  • ONE specific person, id or name only ('show me Jerry', 'fetch his profile', 'pull up 50976') → `rf_candidate_get`. Auto-disambiguates among matches.",
  "  • ANY non-name narrowing OR multi-match intent ('Jerry at Acme', 'K8s candidates', 'who's at Eon for SE', 'people in Sourced') → `rf_candidate_search`. candidate_get cannot use company/owner/stage/technology — search is the only path that can.",
  "",
  "Lean by default. List rows include `{id, name, linkedin_profile}` (linkedin is a full URL); `rf_candidate_get` returns identity + contact + role + current jobs/stages. Defaults are a STARTING SET, never the full record — RF holds many more fields per candidate / job.",
  "",
  "`fields[]` is ADDITIVE over defaults (defaults always present). NO fixed allow-list — pass any reasonable English name matching what you want; real fields resolve, anything else silently drops. Trust the resolver, don't constrain to a hardcoded set. Behavior depends on prompt shape:",
  "  • Generic asks ('fetch his details', 'tell me about X') → request the extra `fields` that plausibly serve the user's intent. Don't return defaults and frame them as exhaustive.",
  "  • Specific asks ('what's his email', 'show his stage') → defaults usually cover; only add what the user explicitly named.",
  "Stay lean — only fields that plausibly serve the prompt — but don't undershoot on generic asks just because you can't predict exact field names.",
  "",
  "`filters: {...}` (on lookup / job-candidates-filter / job-pipeline) is the long-tail bag for fields not yet first-class. Try anything reasonable — unknown keys silently drop.",
  "",
  "Don't request fields already implied by the filter:",
  "  • Filtered by `job` → don't ask for `job` / `jobs`",
  "  • Filtered by `stage` → don't ask for `stage`",
  "  • Filtered by `owner` → don't ask for `owner`",
  "",
  "Disambiguation: `needs_disambiguation: true` returns at HTTP 200 — it's a successful response asking for clarification, not an error. options[] is hard-coded lean (id + name + score, plus minimal context); `fields` is silently ignored on disambiguation envelopes. Render options to the user, let them pick, re-call with the chosen id. Don't guess. If you need richer detail on an option, follow up with `rf_candidate_get(id=...)`.",
  "",
  "Recoverable failures (no candidate matches, unknown stage on this job, no valid tuple to move to, etc.) come back at HTTP 200 as `{ok: false, kind, error, ...recovery_hints}` — e.g. `available_stages` / `available_jobs` / `considered`. Apologize, clarify with the user, retry. 4xx / 5xx are loud install or transport errors and won't reach you with this shape.",
  "",
  "Interview scheduling:",
  "  user: 'schedule a 1st Interview with Jerry on Eon Tech CS for next Monday 3pm CT'",
  "  →  rf_candidate_log_interview({ candidate: 'jerry', job: 'eon tech cs', kind: '1st Interview', start_time: '2026-04-27T15:00:00-05:00' })",
  "  Then inspect `next_step` in the response and follow it:",
  "    • `outlook_url` → surface to the user as a clickable Markdown link, e.g. `[Add to Outlook](outlook_url)`. They click and save.",
  "    • `gcal_hint`   → call the Google Calendar connector's create-event tool with those fields verbatim.",
  "    • Both          → prefer `outlook_url`.",
  "  NEVER add the candidate as an attendee — recruiter-only block.",
  "  `kind` is verbatim ('1st Interview' / '2nd Interview' / ... / 'Final Interview'). `start_time` MUST include a timezone offset.",
  "",
  "When reporting back to the user, translate IDs into names and drop internal noise unless they asked.",
].join("\n");
